name: "Automation: Dependabot refresh"

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh:
    uses: Coalfire-CF/Actions/.github/workflows/automation-dependabot-refresh.yml@c90a5847a5333cc3ed2c48941837490bebaf2759 # pilot Coalfire-CF/Actions#342
    with:
      head_branch: ${{ github.head_ref || github.ref_name }}  # PR head, or current branch if not a PR
      include_github_actions: "true"
      default_interval: "daily"
      depb_path: ".github/dependabot.yml"
      commit_message: "chore: refresh dependabot.yml & TF sources"
